[package]
name = "ckb-fee-estimator"
version = "0.121.0"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2021"
description = "The ckb fee estimator"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
ckb-logger = { path = "../logger", version = "= 0.121.0" }
ckb-types = { path = "../types", version = "= 0.121.0" }
ckb-util = { path = "../../util", version = "= 0.121.0" }
ckb-chain-spec = { path = "../../spec", version = "= 0.121.0" }
thiserror = "1.0"
