[package]
name = "ckb-reward-calculator"
version = "0.121.0-rc1"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2021"
description = "TODO(doc): @keroro520 crate description"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
ckb-types = { path = "../types", version = "= 0.121.0-rc1" }
ckb-store = { path = "../../store", version = "= 0.121.0-rc1" }
ckb-dao = { path = "../dao", version = "= 0.121.0-rc1" }
ckb-dao-utils = { path = "../dao/utils", version = "= 0.121.0-rc1" }
ckb-logger = { path = "../logger", version = "= 0.121.0-rc1" }
ckb-chain-spec = {path = "../../spec", version = "= 0.121.0-rc1"}

[dev-dependencies]
ckb-db = { path = "../../db", version = "= 0.121.0-rc1" }
ckb-occupied-capacity = { path = "../occupied-capacity", version = "= 0.121.0-rc1" }
ckb-db-schema = { path = "../../db-schema", version = "= 0.121.0-rc1" }
tempfile.workspace = true
