[package]
name = "ckb-sync"
version = "0.200.0-rc1"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2021"
description = "The ckb sync/relayer protocols implementation"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
ckb-chain = { path = "../chain", version = "= 0.200.0-rc1" }
ckb-shared = { path = "../shared", version = "= 0.200.0-rc1" }
ckb-store = { path = "../store", version = "= 0.200.0-rc1" }
ckb-app-config = { path = "../util/app-config", version = "= 0.200.0-rc1" }
ckb-types = { path = "../util/types", version = "= 0.200.0-rc1" }
ckb-network = { path = "../network", version = "= 0.200.0-rc1" }
ckb-logger = { path = "../util/logger", version = "= 0.200.0-rc1" }
ckb-metrics = { path = "../util/metrics", version = "= 0.200.0-rc1" }
ckb-util = { path = "../util", version = "= 0.200.0-rc1" }
ckb-verification = { path = "../verification", version = "= 0.200.0-rc1" }
ckb-verification-traits = { path = "../verification/traits", version = "= 0.200.0-rc1" }
ckb-chain-spec = { path = "../spec", version = "= 0.200.0-rc1" }
ckb-channel = { path = "../util/channel", version = "= 0.200.0-rc1" }
ckb-traits = { path = "../traits", version = "= 0.200.0-rc1" }
ckb-error = { path = "../error", version = "= 0.200.0-rc1" }
ckb-tx-pool = { path = "../tx-pool", version = "= 0.200.0-rc1" }
sentry = { version = "0.34.0", optional = true }
ckb-constant = { path = "../util/constant", version = "= 0.200.0-rc1" }
ckb-stop-handler = { path = "../util/stop-handler", version = "= 0.200.0-rc1" }
tokio = { version = "1", features = ["sync"] }
lru = "0.7.1"
futures = "0.3"
governor = "0.3.1"
tempfile.workspace = true
ckb-systemtime = { path = "../util/systemtime", version = "= 0.200.0-rc1" }
dashmap = "4.0"
keyed_priority_queue = "0.3"
itertools.workspace = true

[dev-dependencies]
ckb-test-chain-utils = { path = "../util/test-chain-utils", version = "= 0.200.0-rc1" }
rand = "0.8"
ckb-dao = { path = "../util/dao", version = "= 0.200.0-rc1" }
ckb-dao-utils = { path = "../util/dao/utils", version = "= 0.200.0-rc1" }
ckb-reward-calculator = { path = "../util/reward-calculator", version = "= 0.200.0-rc1" }
ckb-chain = { path = "../chain", version = "= 0.200.0-rc1", features = [
    "mock",
] }
faux = "^0.1"
ckb-systemtime = { path = "../util/systemtime", version = "= 0.200.0-rc1", features = [
    "enable_faketime",
] }
ckb-proposal-table = { path = "../util/proposal-table", version = "= 0.200.0-rc1" }
ckb-logger-service = { path = "../util/logger-service", version = "= 0.200.0-rc1" }

[features]
default = []
stats = []
with_sentry = ["sentry"]
